#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcomps
Version  : 0.1.8
Release  : 10
URL      : https://github.com/rpm-software-management/libcomps/archive/libcomps-0.1.8.tar.gz
Source0  : https://github.com/rpm-software-management/libcomps/archive/libcomps-0.1.8.tar.gz
Summary  : alternative for yum.libcomps written in C
Group    : Development/Tools
License  : GPL-2.0
Requires: libcomps-python3
Requires: libcomps-lib
Requires: libcomps-python
BuildRequires : check-dev
BuildRequires : cmake
BuildRequires : doxygen
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(expat)
BuildRequires : python3-dev

%description
libcomps
========
Libcomps is alternative for yum.comps library. It's written in pure C as library
and there's bindings for python2 and python3.

%package dev
Summary: dev components for the libcomps package.
Group: Development
Requires: libcomps-lib
Provides: libcomps-devel

%description dev
dev components for the libcomps package.


%package lib
Summary: lib components for the libcomps package.
Group: Libraries

%description lib
lib components for the libcomps package.


%package python
Summary: python components for the libcomps package.
Group: Default
Requires: libcomps-python3

%description python
python components for the libcomps package.


%package python3
Summary: python3 components for the libcomps package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libcomps package.


%prep
%setup -q -n libcomps-libcomps-0.1.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507658245
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DPYTHON_DESIRED:STRING=3 -Wno-dev ../libcomps/
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1507658245
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libcomps/comps_bradix.h
/usr/include/libcomps/comps_default.h
/usr/include/libcomps/comps_dict.h
/usr/include/libcomps/comps_doc.h
/usr/include/libcomps/comps_doccategory.h
/usr/include/libcomps/comps_docenv.h
/usr/include/libcomps/comps_docgroup.h
/usr/include/libcomps/comps_docgroupid.h
/usr/include/libcomps/comps_docpackage.h
/usr/include/libcomps/comps_elem.h
/usr/include/libcomps/comps_hslist.h
/usr/include/libcomps/comps_log.h
/usr/include/libcomps/comps_log_codes.h
/usr/include/libcomps/comps_mm.h
/usr/include/libcomps/comps_mradix.h
/usr/include/libcomps/comps_obj.h
/usr/include/libcomps/comps_objdict.h
/usr/include/libcomps/comps_objlist.h
/usr/include/libcomps/comps_objmradix.h
/usr/include/libcomps/comps_objradix.h
/usr/include/libcomps/comps_parse.h
/usr/include/libcomps/comps_radix.h
/usr/include/libcomps/comps_set.h
/usr/include/libcomps/comps_utils.h
/usr/include/libcomps/comps_validate.h
/usr/lib64/libcomps.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcomps.so.0.1.6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
